# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - 3.6
  - 3.7
script: cd web && pip install -r requirements.txt && nvm install 12 && nvm use 12 && npm install && cp .env.example
  .env &&
  source .env
  && npm run lint && flask lint --check && flask test
