[chime2]
# assets
# ------
[chime2.assets]
path = "assets"
app-css = "assets/app.css"
favicon = "assets/favicon.ico"
penn-medicine-header = "assets/penn-medicine-header.css"
# scripts
# -------
[chime2.scripts]
path = "bin"
# localization files
# ------------------
[chime2.localization]
path = "localization"
# logging files
# -------------
[chime2.logging]
path = "var/chime2.log"
# -----------------------
# Dashboard Configuration
# -----------------------
[chime2.dashboard]
title = "CHIME2"
route = "/dashboard/"
# stylesheets
# -----------
[chime2.dashboard.stylesheets]
google-font = "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;1,400;1,600&display=swap"
# scripts
# -------
[chime2.dashboard.scripts]
# menu
# ----
[chime2.dashboard.menu]
header = "Penn Medicine"
item-0 = ["Predictive Healthcare", "http://predictivehealthcare.pennmedicine.org/"]
item-1 = ["How to use CHIME2", "https://code-for-philly.gitbook.io/CHIME-2/"]
